title : moving average
tagline: 
author :
  name : Dru and Tom
  email : 
  github : tomdru 
  twitter : 
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
